version: '3'
services:
  db:
    image: 'mysql/mysql-server:5.7'
    restart: always       
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "123456"   
    networks:
      - net-spring-db 
    user: root   
    volumes:
      - ./mysql/data:/var/lib/mysql:rw
      - ./mysql/my.cnf:/etc/my.cnf
      - ./api/sql:/docker-entrypoint-initdb.d/
    ports:
      - '3306:3306'
  api:
    #build: ./api
    image: 'fulln/mtdhb-api:1.0.0'
    container_name: api
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ./api:/vol/development   
      - ./logs/api/:/tmp/api/log/ --privileged=true
    networks:
      - net-spring-db
    depends_on:
      - db          
      - redis        
  redis:
    restart: always
    image: redis:4.0.9
    container_name: redis
    ports: 
      - "6379:6379"
  get:
    container_name: get   
    #pid: "host"
    image: 'fulln/mtdhb-get:1.0.0'
    #build: ./get
    ports:
      - "3333:3333"
      - "12266:22"
    command: /bin/bash /run.sh   
    volumes: 
      - ./logs/:/opt/get/log/ 
  # nginx:    
  #   restart: always
  #   image: nginx:1.12.2
  #   ports:
  #     - 8080:80
  #     - 80:80
  #     - 443:443
  #   volumes:
  #     - $PWD/logs:/var/log/nginx
  #     - $PWD/nginx/nginx.conf:/etc/nginx/nginx.conf:ro  
networks:
  net-spring-db:
    driver: bridge
    
